import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DM_Sans } from 'next/font/google';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dm_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}